INSERT INTO MUDA (frutifera, nome_muda)
VALUES(1,'tetste');

INSERT INTO REGIAO (nome_regiao)
VALUES('SP');

INSERT INTO MUDA_REGIAO (MUDA_ID, REGIAO_ID)
VALUES(1,1);

INSERT INTO SOLO (TIPO_SOLO)
VALUES('Solo1');