INSERT INTO REGIAO (nome_regiao)
VALUES('SP');

INSERT INTO SOLO (TIPO_SOLO)
VALUES('Solo1');

INSERT INTO FAMILIA (NAME_FAMILIA)
VALUES('FAMILIA1');

INSERT INTO ESPECIE (NAME_ESPECIE, FAMILIA_ID)
VALUES('Especie1',1);

INSERT INTO BIOMA (NOME_BIOMA)
VALUES('Bioma1');